# Generated by Django 5.1.7 on 2026-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
